### ISSUE TITLE
This might be a potential bug - in one of the circuit implementaiton

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#12]
@ stoke-release/src/validator/handlers/packed_handler.cc
```
    if(j + output_width < dest.size()) {
      if(clear)
        result = SymBitVector::constant(dest.size() - j, 0);
//    result wasn't concatenated here at the end ... 
      else
        result = state[dest][dest.size() - 1][j] || result;
    }
```

**Comment by bchurchill** [comment]
I think you're right about this, although I don't think it actually affects any instructions (at least at first glance).  I think that line is actually dead code at the moment -- otherwise the SMTSolver class would be reporting type errors when we go to fuzz.  Does that agree with your intuition?

**Comment by rknath** [comment]
yes it is deadcode since none of the implemented instructions clears the destination. 
I was implementing pmovmskb inside packed_handler
so unluckily stepped into this .. was getting type errors.

**Comment by bchurchill** [comment]
Ah, ok.  I'll go write a fix now and add it to the repository.

**Comment by bchurchill** [comment]
I just did exactly what you said -- concatenating on 'result' seems like the right thing and I pushed to this repository.  Our test suite passes, but that's not helpful since I don't have any circuits to test this code.  Please reopen this ticket if it doesn't work as expected.  Thank you for finding this.
