### ISSUE TITLE
Search with Formal Validation

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#16]
I guess Lowest Known Correct Cost (19) isn't actually a correct code cost with formal validation. Right ?

**Comment by bchurchill** [comment]
Nope.  That just means it passes any testcases so far.  Formal 
validation is expensive so it's only done at the end.  If you use 
--strategy formal, it will say at the end something like 'found a 
verified rewrite' or something contrary to that.

**Comment by rknath** [comment]
Thanks. 

My understanding is that the test cases are randomly generated during the search. My intuition tells me that it may make the search inefficient in terms of finding an optimized code. 

Based on your experience .. 
which one has more success in finding optimized code ? 
testcase based validation or formal validation ?

do you do formal validation after each timeout_cycles ? 
 - do you keep the state of stoke and resume from there ? 
or at the end of everything timeout X timeout_cycles ? 

--timeout 50000000000 # Propose 400K modifications before giving up
--timeout_action testcase # Try adding a new testcase from the testset when search times out
--timeout_cycles 0 # Timeout up to 32 times before giving up
--timeout_sec 36000 # actual running time 
--strategy formal # Verify results using a larger hold out testcase set

**Comment by bchurchill** [comment]
No, testcases are never "randomly generated" during search.  Testcases can be generated using the formal validator when the search has constructed a rewrite that failed to validate, and are fed back into the search.  Indeed, the formal validator runs after each "timeout_cycle", until a correct rewrite is found (in which case stoke quits early).

Of course, writing testcases by hand is preferable, because you have knowledge the validator doesn't and can make a more complete test suite without first running the code.  You can usually converge to a solution faster using your own testcases.  You can also get better speedups if you don't use the formal validator because the final rewrite doesn't have to be totally correct; if it's 'correct enough' for your purposes then you can sacrifice precision for correctness.

The benefit of the formal validator is that your rewrite is correct, and any guarantee like this is necessarily expensive.
